{% set name = "pandapower" %}
{% set version = "2.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: fc3ffefe00eee5c3c4a81053f80f9f2fd93ec6b47b8557fc54c4449bfbd08b0f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - cryptography
    - networkx >=2.5
    - numba
    - numpy
    - openpyxl
    - packaging
    - pandas >=1.0
    - python
    - scipy
    - xlsxwriter

test:
  imports:
    - pandapower
    - pandapower.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TonyXiang8787
    - kyri-petrou
