{% set name = "pandapower" %}
{% set version = "2.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: 5a1f8b4decb3d00ed9a82262a496bbf107cf546e758154b299dbf43fe4d04db9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - cryptography
    - networkx
    - numba
    - numpy >=0.11
    - openpyxl
    - packaging
    - pandas >=0.17
    - python
    - scipy
    - xlrd
    - xlsxwriter

test:
  imports:
    - pandapower
    - pandapower.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
