{% set name = "pandapower" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: 494ff0e21d1ecc0bf1f84c56886bde86b660858244bf96730238c1e2833caf3f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - cryptography
    - networkx
    - numpy >=0.11
    - packaging
    - pandas >=0.17
    - python
    - scipy
    - xlrd
    - xlsxwriter

test:
  imports:
    - pandapower
    - pandapower.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
