{% set name = "pandapower" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandapower-{{ version }}.zip
  sha256: 02e0e7a203a4e10323b8b6556d3e5c4bf1995a00b749f47b8da53d1e984b0eea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cryptography
    - networkx
    - numba
    - numpy >=0.11
    - openpyxl
    - packaging
    - pandas >=0.17
    - python
    - scipy
    - xlrd
    - xlsxwriter

test:
  imports:
    - pandapower
    - pandapower.control
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.pandapower.org
  summary: An easy to use open source tool for power system modeling, analysis and optimization with a high degree of automation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kyri-petrou
